apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-test-1
spec:
  template:
    spec:
      containers:
      - name: tester
        image: trainer:latest
        command: ["python", "/app/test.py"]
        volumeMounts:
        - name: model-volume
          mountPath: /model
      restartPolicy: Never
      volumes:
      - name: model-volume
        emptyDir: {}
