apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-ddp-single-1
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: trainer:latest
        env:
        - name: EPOCHS
          value: "2"
        - name: BATCH_SIZE
          value: "64"
        - name: DATASET_SIZE
          value: "20000"
        volumeMounts:
        - name: model-volume
          mountPath: /model
      restartPolicy: Never
      volumes:
      - name: model-volume
        emptyDir: {}
